/*
 * text processor
 * Text Processing API for CS6650 Summer 1 2021
 *
 * OpenAPI spec version: 1.0.2
 * Contact: i.gorton@northestern.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
